-- MySQL Script generated by MySQL Workbench
-- Sun Nov 28 07:33:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hearts
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hearts` ;

-- -----------------------------------------------------
-- Schema hearts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hearts` DEFAULT CHARACTER SET utf8 ;
USE `hearts` ;

-- -----------------------------------------------------
-- Table `hearts`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hearts`.`role` ;

CREATE TABLE IF NOT EXISTS `hearts`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hearts`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hearts`.`user` ;

CREATE TABLE IF NOT EXISTS `hearts`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `time_created` DATETIME NOT NULL,
  `last_accessed` DATETIME NOT NULL,
  `profile_picture` MEDIUMBLOB NULL,
  `profile_picture_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `hearts`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hearts`.`stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hearts`.`stats` ;

CREATE TABLE IF NOT EXISTS `hearts`.`stats` (
  `user_id` INT UNSIGNED NOT NULL,
  `win` INT NULL DEFAULT 0,
  `lost` INT NULL DEFAULT 0,
  `average_placement` DOUBLE NULL DEFAULT 0,
  `points_taken_per_game` DOUBLE NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  INDEX `fk_stats_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_stats_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hearts`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hearts`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hearts`.`game` ;

CREATE TABLE IF NOT EXISTS `hearts`.`game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL DEFAULT 'NOT_STARTED',
  `logs` VARCHAR(4550) NOT NULL,
  `session_created` DATETIME NULL,
  `session_ended` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hearts`.`user_has_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hearts`.`user_has_game` ;

CREATE TABLE IF NOT EXISTS `hearts`.`user_has_game` (
  `user_id` INT UNSIGNED NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `game_id`),
  INDEX `fk_user_has_game_game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_user_has_game_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_game_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hearts`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `hearts`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hearts`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `hearts`;
INSERT INTO `hearts`.`role` (`id`, `name`) VALUES (1, 'ADMIN');
INSERT INTO `hearts`.`role` (`id`, `name`) VALUES (2, 'PLAYER');

COMMIT;

